### ISSUE TITLE
created_at and requested_at both have auto_now_add=True

### ISSUE THREAD

**Issue by billray0259** [mua2010/PEPro#3]
In [models.py](https://github.com/mua2010/PEPro/blob/master/homepage/models.py) on lines 27 and 28 created_at and requested_at are set to DateTimeFields, and both have auto_now_add set to True.

Wouldn't this automatically set the time the review was requested, and the time the review was created to the same time? Which is impossible, right?

**Comment by mua2010** [comment]
> In [models.py](https://github.com/mua2010/PEPro/blob/master/homepage/models.py) on lines 27 and 28 created_at and requested_at are set to DateTimeFields, and both have auto_now_add set to True.
> 
> Wouldn't this automatically set the time the review was requested, and the time the review was created to the same time? Which is impossible, right?

I just checked it online. https://simpleisbetterthancomplex.com/tips/2016/05/23/django-tip-4-automatic-datetime-fields.html

The auto_now_add will set the timezone.now() only when the instance is created, and auto_now will update the field every time the save method is called.

I guess we will change the 
**created_at = models.DateTimeField(auto_now_add=True, blank=True)**
to 
**created_at = models.DateTimeField(auto_now=True, blank=True)**

**Good catch Bill! You are awesome.**
